import "@/app/globals.css";
import { CartProvider } from "@/context/CartContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"; // Import Footer Component

export const metadata = {
  title: "Supplements",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <CartProvider>
          <Navbar />
          <main className="flex-grow">{children}</main> {/* Ensure content expands */}
          <Footer /> {/* Footer is added here */}
        </CartProvider>
      </body>
    </html>
  );
}
